server:
  port: 10574
  context-path: /blf-barcode-api
logging:
  level:
    root: info

eureka:
  client:
    service-url:
       defaultZone: http://newdev.blf1.belle.net.cn/bf-register-center/eureka/   # 指定注册中心的地址

  instance:
    preferIpAddress: true

info:
  sysEnv: 开发环境

spring:
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.20.38.12:3306/db_barcode?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'blf1#root'
    hikari:
      maximum-pool-size: 50
  data:
    mongodb:
      uri: mongodb://bldoc:blf1#root@172.20.38.10:27017/belledoc
      gridFsDatabase: belledoc
  cache:
    type: redis
  redis:
    host: 172.20.38.10
    port: 6379
    database: 1
  rabbitmq:
    host: 172.20.38.15
    port: 5672
    username: guest
    password: guest
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
rabbit:
  general:
    direct:
      queue: export_message_queue #队列名称
shiro:
  auth:
    way: none #开发请改成none，其它环境shiro
  jwt:
    secret: 12345678901234567890123456789012
    expire: 86400

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.belle.blf.barcode.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器生产环境不能开启
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
