server:
  port: 10579
  context-path: /blf-barcodeif-api
logging:
  level:
    root: info

eureka:
  client:
    service-url:
       defaultZone: http://newst.blf1.belle.net.cn/bf-register-center/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true

info:
  sysEnv: 测试环境

spring:
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://st.db.belle.cn:3307/db_barcode?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: blf_barcode
    password: 'blfbarcode#40'
  data:
    mongodb:
      uri: mongodb://bldoc:blf1#root@172.20.38.12:27017/belledoc
      gridFsDatabase: belledoc
  cache:
    type: redis
  redis:
    host: 172.20.38.12
    port: 6379
  # dubbo:
    # server: true
    # application:
      # name: blf-barcodeif-api
    # registry:
      # address: zookeeper://10.234.9.61:2181
      # check: false
    # protocol:
      # name: dubbo
      # port: 20983
    # scan: com.belle.blf.barcodeif.dubbo.service.impl
    
  dubbo:
    server: true
    application:
      name: blf-barcodeif-api
    registries: 
      - address: zookeeper://10.234.9.61:2181
        id: zk-pms
        check: false
      - address: zookeeper://10.234.6.210:2181
        id: zk-wms
        check: false
    registry:
      address: zookeeper://10.234.9.61:2181
      check: false
    protocol: 
      name: dubbo
      port: 20983
    scan: com.belle.blf.barcodeif.dubbo.service.impl
    
  jms:
    pub-sub-domain: false
  activemq: 
    broker-url: tcp://10.234.9.63:3046
    user: admin
    password: admin
    pool: 
      enable: true
      max-connections: 10
      expiry-timeout: 0
      idle-timeout: 30000
    packages: 
      trust-all: true

#### 调度中心
lts:
  tasktracker:
    cluster-name: eyd_cluster
    registry-address: zookeeper://172.20.38.11:22181
    node-group: blf_if_TaskTracker
    job-runner-class: com.belle.blf.barcodeif.jobrunner.JobRunnerImpl

shiro:
  auth:
    way: shiro #开发请改成none，其它环境shiro
  jwt:
    secret: 12345678901234567890123456789012
    #expire: 36000

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.belle.blf.barcodeif.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器生产环境不能开启
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

mdm-topic: Consumer.BLFBarcode.VirtualTopic.cn.belle.bi.mdm.topic

send-to-wms-invalid-box-url: https://test-dop-server.belle.net.cn/gateway
send-to-wms-invalid-box-appid: devappid
send-to-wms-invalid-box-appkey: devappkey